name: nest

services:
  nest-server:
    container_name: nest_server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - DB_HOSTNAME=host.docker.internal
      - REDIS_HOSTNAME=host.docker.internal
    ports:
      - 3001:3001
