server:
  port: 8024
  address: 127.0.0.1
  error:
    include-message: always

spring:
  elasticsearch:
    uris: http://localhost:9200
  data:
    redis:
      port: 6379
      database: 0
      password:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:test.db
  web:
    resources:
      static-locations: classpath:/custom-static/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: site.psvm.entity
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

# 静态文件路径配置
static-path:
  original: /album/original/
  originalDiskPath: D:\4 Study\nginx-1.24.0-album\html\album\original\
  compressed: /album/compress/
  compressedDiskPath: D:\4 Study\nginx-1.24.0-album\html\album\compress\
